Spring:
  #Application Properties
  application:
    name: movie-ticket-booking-system-api

  #Datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/raju-springboot-movie-ticket-booking-system-api?createDatabaseIfNotExist=true
    username: root
    password: Akash@2002

  #JPA Details
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update